source = /nix/persist/home/user/.dotfiles/hypr/.config/hypr/dms/colors.conf
source = /nix/persist/home/user/.dotfiles/hypr/.config/hypr/dms/layout.conf
source = /nix/persist/home/user/.dotfiles/hypr/.config/hypr/dms/outputs.conf
